/**
 * Region & constellation reference data for the Shadow Location Network.
 *
 * Provides in-memory lookups from regionId / constellationId → name + bounding
 * box, and substring search for autocomplete pickers.
 *
 * Data source: static JSON generated by scripts/fetch-regions.mjs from the
 * Stillness World API.
 *
 * Regenerate:  node scripts/fetch-regions.mjs
 */

import rawRegions from "../data/regions.json";
import rawConstellations from "../data/constellations.json";

// ============================================================
// Types
// ============================================================

export interface BoundingBox {
  xMin: bigint;
  xMax: bigint;
  yMin: bigint;
  yMax: bigint;
  zMin: bigint;
  zMax: bigint;
}

export interface RegionEntry {
  id: number;
  name: string;
  bounds: BoundingBox;
}

export interface ConstellationEntry {
  id: number;
  regionId: number;
  name: string;
  bounds: BoundingBox;
}

// ============================================================
// Parse raw tuples
// ============================================================

type RegionTuple = [number, string, string, string, string, string, string, string];
type ConstellationTuple = [number, number, string, string, string, string, string, string, string];

function parseBounds(
  xMinS: string,
  xMaxS: string,
  yMinS: string,
  yMaxS: string,
  zMinS: string,
  zMaxS: string,
): BoundingBox {
  return {
    xMin: BigInt(xMinS),
    xMax: BigInt(xMaxS),
    yMin: BigInt(yMinS),
    yMax: BigInt(yMaxS),
    zMin: BigInt(zMinS),
    zMax: BigInt(zMaxS),
  };
}

const regions: RegionEntry[] = (rawRegions as RegionTuple[]).map(
  ([id, name, xMin, xMax, yMin, yMax, zMin, zMax]) => ({
    id,
    name,
    bounds: parseBounds(xMin, xMax, yMin, yMax, zMin, zMax),
  }),
);

const constellations: ConstellationEntry[] = (rawConstellations as ConstellationTuple[]).map(
  ([id, regionId, name, xMin, xMax, yMin, yMax, zMin, zMax]) => ({
    id,
    regionId,
    name,
    bounds: parseBounds(xMin, xMax, yMin, yMax, zMin, zMax),
  }),
);

// ============================================================
// Lookup structures (built once on import)
// ============================================================

const regionById = new Map<number, RegionEntry>();
const constellationById = new Map<number, ConstellationEntry>();

/** Lowercased names pre-computed for fast search. */
const regionSearchIndex: { lower: string; entry: RegionEntry }[] = [];
const constellationSearchIndex: { lower: string; entry: ConstellationEntry }[] = [];

for (const entry of regions) {
  regionById.set(entry.id, entry);
  regionSearchIndex.push({ lower: entry.name.toLowerCase(), entry });
}

for (const entry of constellations) {
  constellationById.set(entry.id, entry);
  constellationSearchIndex.push({ lower: entry.name.toLowerCase(), entry });
}

// ============================================================
// Public API
// ============================================================

/** All loaded regions. */
export const REGIONS = regionById;

/** All loaded constellations. */
export const CONSTELLATIONS = constellationById;

/** Total counts. */
export const REGION_COUNT = regions.length;
export const CONSTELLATION_COUNT = constellations.length;

/** Resolve a region ID to its name, or return a fallback string. */
export function regionName(id: number): string {
  return regionById.get(id)?.name ?? `Region #${id}`;
}

/** Resolve a constellation ID to its name, or return a fallback string. */
export function constellationName(id: number): string {
  return constellationById.get(id)?.name ?? `Constellation #${id}`;
}

/** Get the canonical bounding box for a region. */
export function getRegionBounds(regionId: number): BoundingBox | undefined {
  return regionById.get(regionId)?.bounds;
}

/** Get the canonical bounding box for a constellation. */
export function getConstellationBounds(constellationId: number): BoundingBox | undefined {
  return constellationById.get(constellationId)?.bounds;
}

/** Get all constellations belonging to a region. */
export function getConstellationsInRegion(regionId: number): ConstellationEntry[] {
  return constellations.filter((c) => c.regionId === regionId);
}

/**
 * Case-insensitive substring search across region names.
 * Returns up to `limit` matching entries, prioritising prefix matches.
 */
export function searchRegions(query: string, limit = 15): RegionEntry[] {
  if (!query) return regions.slice(0, limit);

  const q = query.toLowerCase();
  const prefixMatches: RegionEntry[] = [];
  const substringMatches: RegionEntry[] = [];

  for (const { lower, entry } of regionSearchIndex) {
    if (lower.startsWith(q)) {
      prefixMatches.push(entry);
    } else if (lower.includes(q)) {
      substringMatches.push(entry);
    }
    if (prefixMatches.length + substringMatches.length >= limit * 2) break;
  }

  return [...prefixMatches, ...substringMatches].slice(0, limit);
}

/**
 * Case-insensitive substring search across constellation names.
 * Returns up to `limit` matching entries, prioritising prefix matches.
 */
export function searchConstellations(query: string, limit = 15): ConstellationEntry[] {
  if (!query) return constellations.slice(0, limit);

  const q = query.toLowerCase();
  const prefixMatches: ConstellationEntry[] = [];
  const substringMatches: ConstellationEntry[] = [];

  for (const { lower, entry } of constellationSearchIndex) {
    if (lower.startsWith(q)) {
      prefixMatches.push(entry);
    } else if (lower.includes(q)) {
      substringMatches.push(entry);
    }
    if (prefixMatches.length + substringMatches.length >= limit * 2) break;
  }

  return [...prefixMatches, ...substringMatches].slice(0, limit);
}
