/**
 * Solar system reference data for the Shadow Location Network.
 *
 * Provides an in-memory lookup from solarSystemId → name + coordinates,
 * and a substring search for the autocomplete picker.
 *
 * Data source: static JSON generated by scripts/fetch-solar-systems.mjs
 * from the Stillness World API. Tuple format:
 *   [id, name, constellationId, regionId, x, y, z]
 * where coordinates are string-encoded integers (can exceed MAX_SAFE_INTEGER).
 *
 * Regenerate:  node scripts/fetch-solar-systems.mjs
 */

import rawSystems from "../data/solar-systems.json";

// ============================================================
// Types
// ============================================================

export interface SolarSystemEntry {
  id: number;
  name: string;
  constellationId: number;
  regionId: number;
  x: bigint;
  y: bigint;
  z: bigint;
}

/** 1 light-year in meters (game coordinate unit). */
const METERS_PER_LY = 9_460_730_472_580_800n;

// ============================================================
// Lookup structures (built once on first import)
// ============================================================

type RawTuple = [number, string, number, number, string, string, string];

const systems: SolarSystemEntry[] = (rawSystems as RawTuple[]).map(
  ([id, name, constellationId, regionId, xs, ys, zs]) => ({
    id,
    name,
    constellationId,
    regionId,
    x: BigInt(xs),
    y: BigInt(ys),
    z: BigInt(zs),
  }),
);

/** Map from solarSystemId → entry for O(1) lookups. */
const byId = new Map<number, SolarSystemEntry>();

/** Lowercased names pre-computed for fast search. */
const searchIndex: { lower: string; entry: SolarSystemEntry }[] = [];

for (const entry of systems) {
  byId.set(entry.id, entry);
  searchIndex.push({
    lower: entry.name.toLowerCase(),
    entry,
  });
}

// ============================================================
// Public API
// ============================================================

/** All loaded solar systems. */
export const SOLAR_SYSTEMS = byId;

/** Total number of loaded solar systems. */
export const SOLAR_SYSTEM_COUNT = systems.length;

/** Resolve a solar system ID to its name, or return a fallback string. */
export function solarSystemName(id: number): string {
  return byId.get(id)?.name ?? `System #${id}`;
}

/**
 * Euclidean distance between two solar systems in light-years.
 * Uses BigInt arithmetic for the squared components, then converts
 * to Number for the final sqrt (precision loss < 0.0001 LY).
 */
export function solarSystemDistance(a: number, b: number): number | null {
  const sa = byId.get(a);
  const sb = byId.get(b);
  if (!sa || !sb) return null;

  const dx = sa.x - sb.x;
  const dy = sa.y - sb.y;
  const dz = sa.z - sb.z;
  const d2 = dx * dx + dy * dy + dz * dz;

  // Convert metres → light-years: sqrt(d2) / METERS_PER_LY
  // We do this as: sqrt(d2 / METERS_PER_LY²) to stay in BigInt longer
  const ly2 = d2 / (METERS_PER_LY * METERS_PER_LY);
  return Math.sqrt(Number(ly2));
}

/**
 * Case-insensitive substring search across system names.
 * Returns up to `limit` matching entries (default 15), prioritising
 * prefix matches over substring matches.
 */
export function searchSolarSystems(
  query: string,
  limit = 15,
): SolarSystemEntry[] {
  if (!query) return systems.slice(0, limit);

  const q = query.toLowerCase();
  const prefixMatches: SolarSystemEntry[] = [];
  const substringMatches: SolarSystemEntry[] = [];

  for (const { lower, entry } of searchIndex) {
    if (lower.startsWith(q)) {
      prefixMatches.push(entry);
    } else if (lower.includes(q)) {
      substringMatches.push(entry);
    }
    if (prefixMatches.length + substringMatches.length >= limit * 2) break;
  }

  return [...prefixMatches, ...substringMatches].slice(0, limit);
}
