/**
 * Shadow Location Network — server-side region & constellation reference data.
 *
 * Reads the same JSON files generated by scripts/fetch-regions.mjs to provide
 * canonical bounding boxes for ZK proof validation.
 *
 * The indexer uses this to:
 *   1. Look up the canonical bounding box when a client submits a proof by
 *      regionId or constellationId
 *   2. Validate that the proof's publicSignals match the canonical bounds
 */

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// JSON files live at <project>/web/src/data/ — two levels up from indexer/src/location/
const DATA_DIR = resolve(__dirname, "../../../web/src/data");

// ============================================================
// Types
// ============================================================

export interface BoundingBox {
  xMin: bigint;
  xMax: bigint;
  yMin: bigint;
  yMax: bigint;
  zMin: bigint;
  zMax: bigint;
}

export interface RegionEntry {
  id: number;
  name: string;
  bounds: BoundingBox;
}

export interface ConstellationEntry {
  id: number;
  regionId: number;
  name: string;
  bounds: BoundingBox;
}

// ============================================================
// Lazy-loaded data
// ============================================================

let regionMap: Map<number, RegionEntry> | null = null;
let constellationMap: Map<number, ConstellationEntry> | null = null;

type RegionTuple = [number, string, string, string, string, string, string, string];
type ConstellationTuple = [number, number, string, string, string, string, string, string, string];

function parseBounds(
  xMinS: string,
  xMaxS: string,
  yMinS: string,
  yMaxS: string,
  zMinS: string,
  zMaxS: string,
): BoundingBox {
  return {
    xMin: BigInt(xMinS),
    xMax: BigInt(xMaxS),
    yMin: BigInt(yMinS),
    yMax: BigInt(yMaxS),
    zMin: BigInt(zMinS),
    zMax: BigInt(zMaxS),
  };
}

function loadRegions(): Map<number, RegionEntry> {
  const path = resolve(DATA_DIR, "regions.json");
  const raw: RegionTuple[] = JSON.parse(readFileSync(path, "utf-8"));
  const map = new Map<number, RegionEntry>();

  for (const [id, name, xMin, xMax, yMin, yMax, zMin, zMax] of raw) {
    map.set(id, { id, name, bounds: parseBounds(xMin, xMax, yMin, yMax, zMin, zMax) });
  }

  return map;
}

function loadConstellations(): Map<number, ConstellationEntry> {
  const path = resolve(DATA_DIR, "constellations.json");
  const raw: ConstellationTuple[] = JSON.parse(readFileSync(path, "utf-8"));
  const map = new Map<number, ConstellationEntry>();

  for (const [id, regionId, name, xMin, xMax, yMin, yMax, zMin, zMax] of raw) {
    map.set(id, {
      id,
      regionId,
      name,
      bounds: parseBounds(xMin, xMax, yMin, yMax, zMin, zMax),
    });
  }

  return map;
}

// ============================================================
// Public API
// ============================================================

export function getRegion(regionId: number): RegionEntry | undefined {
  if (!regionMap) regionMap = loadRegions();
  return regionMap.get(regionId);
}

export function getConstellation(constellationId: number): ConstellationEntry | undefined {
  if (!constellationMap) constellationMap = loadConstellations();
  return constellationMap.get(constellationId);
}

export function getRegionBounds(regionId: number): BoundingBox | undefined {
  return getRegion(regionId)?.bounds;
}

export function getConstellationBounds(constellationId: number): BoundingBox | undefined {
  return getConstellation(constellationId)?.bounds;
}

/**
 * Convert a BoundingBox to the decimal field-element strings expected by the
 * ZK circuit's public signals.
 *
 * The circuit uses BN254 field arithmetic, so negative coordinates are
 * represented as p - |value|.
 */
const BN254_PRIME =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

export function boundsToFieldStrings(bounds: BoundingBox): {
  xMin: string;
  xMax: string;
  yMin: string;
  yMax: string;
  zMin: string;
  zMax: string;
} {
  function toField(v: bigint): string {
    return (v >= 0n ? v : v + BN254_PRIME).toString();
  }

  return {
    xMin: toField(bounds.xMin),
    xMax: toField(bounds.xMax),
    yMin: toField(bounds.yMin),
    yMax: toField(bounds.yMax),
    zMin: toField(bounds.zMin),
    zMax: toField(bounds.zMax),
  };
}
