#!/usr/bin/env bash
set -euo pipefail

# Publish all Move packages to SUI localnet and write package IDs to .env
# Called by mprocs contracts-publish or run standalone.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.localnet"
WEB_ENV_FILE="$PROJECT_ROOT/web/.env.localnet"
PUB_FILE="$PROJECT_ROOT/Pub.localnet.toml"
GAS_BUDGET=2000000000  # 2 SUI — publishing with deps needs more than 0.5

PACKAGES=("tribe" "corm_auth" "trustless_contracts" "witnessed_contracts" "corm_state" "assembly_metadata")
ENV_VARS=("PACKAGE_TRIBE" "PACKAGE_CORM_AUTH" "PACKAGE_TRUSTLESS_CONTRACTS" "PACKAGE_WITNESSED_CONTRACTS" "PACKAGE_CORM_STATE" "PACKAGE_ASSEMBLY_METADATA")
VITE_VARS=("VITE_TRIBE_PACKAGE_ID" "VITE_CORM_AUTH_PACKAGE_ID" "VITE_TRUSTLESS_CONTRACTS_PACKAGE_ID" "VITE_WITNESSED_CONTRACTS_PACKAGE_ID" "VITE_CORM_STATE_PACKAGE_ID" "VITE_ASSEMBLY_METADATA_PACKAGE_ID")

write_env_var() {
  local var="$1" val="$2" file="$3"
  if grep -q "^${var}=" "$file" 2>/dev/null; then
    sed -i "s|^${var}=.*|${var}=${val}|" "$file"
  else
    # Ensure file ends with a newline before appending
    [ -s "$file" ] && [ -n "$(tail -c1 "$file")" ] && echo >> "$file"
    echo "${var}=${val}" >> "$file"
  fi
}

# ── Clear stale package IDs from previous runs ────────────────────
if [ -f "$ENV_FILE" ]; then
  echo "Clearing stale contract IDs from $ENV_FILE..."
  for var in "${ENV_VARS[@]}" "${VITE_VARS[@]}" VITE_TRIBE_REGISTRY_ID CORM_STATE_PACKAGE_ID VITE_METADATA_REGISTRY_ID VITE_CORM_CONFIG_ID; do
    [ -z "$var" ] && continue
    sed -i "s|^${var}=.*|${var}=|" "$ENV_FILE"
  done
fi

echo "Waiting for SUI localnet..."
until curl -so /dev/null -w '%{http_code}' http://127.0.0.1:9000 >/dev/null 2>&1; do
  sleep 2
done

# Ensure the client is pointing at localnet
if ! sui client envs 2>/dev/null | grep -q 'local'; then
  echo "Adding local env to SUI client..."
  sui client new-env --alias local --rpc http://127.0.0.1:9000 2>/dev/null
fi
sui client switch --env local 2>/dev/null
echo "Switched to local env"

# Wait for faucet to be ready, then request gas
echo "Waiting for faucet..."
until curl -so /dev/null http://127.0.0.1:9123 2>/dev/null; do
  sleep 2
done
echo "Requesting faucet funds..."
sui client faucet 2>&1 || true

# Wait for coins to arrive
echo "Waiting for gas coins..."
until sui client gas --json 2>/dev/null | jq -e 'length > 0' >/dev/null 2>&1; do
  sleep 2
done
echo "Gas available"

# Remove stale ephemeral publication files (--force-regenesis means new chain each time)
rm -f "$PUB_FILE" "$PROJECT_ROOT/Pub.local.toml"

# ── Wait for the world deployment and seed Pub.localnet.toml ──────────
# The world package is deployed separately by deploy-world-contracts.sh.
# Without this, --with-unpublished-dependencies re-publishes the world
# dependency as a new package, causing type mismatches (e.g. Character
# objects from the original world deployment don't match the tribe
# contract's bundled copy).
#
# Because both scripts start concurrently via mprocs, we must wait
# until the world package actually exists on the current chain —
# the extracted-object-ids.json may still contain a stale ID from a
# previous --force-regenesis run.
WORLD_IDS_FILE="$PROJECT_ROOT/../world-contracts/deployments/localnet/extracted-object-ids.json"
WORLD_PATH=$(cd "$PROJECT_ROOT/../world-contracts/contracts/world" && pwd)
SUI_VERSION=$(sui --version 2>/dev/null | grep -oP '\d+\.\d+\.\d+' || echo "1.65.2")
CHAIN_ID=$(curl -s http://127.0.0.1:9000 -X POST \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"sui_getChainIdentifier","params":[]}' \
  | jq -r '.result')

world_pkg_exists_on_chain() {
  local pkg_id="$1"
  [ -n "$pkg_id" ] && [ "$pkg_id" != "null" ] && \
  curl -s http://127.0.0.1:9000 -X POST \
    -H 'Content-Type: application/json' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"sui_getObject\",\"params\":[\"$pkg_id\"]}" \
  | jq -e '.result.data' >/dev/null 2>&1
}

MAX_WAIT=180
WAITED=0
WORLD_PKG_ID=""
echo "Waiting for world package to be deployed on chain $CHAIN_ID..."
while true; do
  if [ -f "$WORLD_IDS_FILE" ]; then
    WORLD_PKG_ID=$(jq -r '.world.packageId' "$WORLD_IDS_FILE")
    if world_pkg_exists_on_chain "$WORLD_PKG_ID"; then
      echo "World package $WORLD_PKG_ID verified on chain"
      break
    fi
  fi
  if [ "$WAITED" -ge "$MAX_WAIT" ]; then
    echo "ERROR: World package not found on chain after ${MAX_WAIT}s" >&2
    echo "Make sure deploy-world-contracts.sh has completed successfully." >&2
    exit 1
  fi
  sleep 5
  WAITED=$((WAITED + 5))
done

echo "Seeding Pub.localnet.toml with world package: $WORLD_PKG_ID"
cat > "$PUB_FILE" <<EOF
# generated by Move / publish-contracts-local.sh
build-env = "localnet"
chain-id = "$CHAIN_ID"

[[published]]
source = { local = "$WORLD_PATH" }
published-at = "$WORLD_PKG_ID"
original-id = "$WORLD_PKG_ID"
version = 1
toolchain-version = "$SUI_VERSION"
build-config = { flavor = "sui", edition = "2024" }
EOF

for i in "${!PACKAGES[@]}"; do
  pkg="${PACKAGES[$i]}"
  var="${ENV_VARS[$i]}"
  pkg_path="$PROJECT_ROOT/contracts/$pkg"

  echo "Publishing $pkg..."
  sui client test-publish "$pkg_path" \
    --gas-budget "$GAS_BUDGET" \
    --build-env localnet \
    --with-unpublished-dependencies \
    > /dev/null 2>&1 || {
    echo "ERROR: test-publish failed for $pkg" >&2
    # Retry without suppressing output so the error is visible
    sui client test-publish "$pkg_path" \
      --gas-budget "$GAS_BUDGET" \
      --build-env localnet \
      --with-unpublished-dependencies 2>&1 || true
    exit 1
  }

  # test-publish records the package ID in Pub.localnet.toml — read it from there
  PACKAGE_ID=$(grep -A1 "$pkg_path" "$PUB_FILE" | grep 'published-at' | sed 's/.*"\(0x[^"]*\)".*/\1/')
  vite_var="${VITE_VARS[$i]}"
  echo "  $var=$PACKAGE_ID"
  write_env_var "$var" "$PACKAGE_ID" "$ENV_FILE"
  [ -n "$vite_var" ] && write_env_var "$vite_var" "$PACKAGE_ID" "$ENV_FILE"

  # Also update the web env file so vite picks up the IDs
  if [ -f "$WEB_ENV_FILE" ] && [ -n "$vite_var" ]; then
    write_env_var "$vite_var" "$PACKAGE_ID" "$WEB_ENV_FILE"
  fi

  # Write CORM_STATE_PACKAGE_ID alias (used by continuity-engine config)
  if [ "$pkg" = "corm_state" ]; then
    write_env_var "CORM_STATE_PACKAGE_ID" "$PACKAGE_ID" "$ENV_FILE"
    echo "  CORM_STATE_PACKAGE_ID=$PACKAGE_ID"
  fi

  # ── Extract shared object IDs created during init ────────────────
  if [ "$pkg" = "tribe" ]; then
    echo "  Querying TribeRegistry shared object ID..."
    TRIBE_REGISTRY_ID=$(
      curl -s http://127.0.0.1:9000 -X POST \
        -H 'Content-Type: application/json' \
        -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"suix_queryEvents\",\"params\":[{\"MoveEventType\":\"${PACKAGE_ID}::tribe::TribeRegistryCreatedEvent\"},null,1,false]}" \
      | jq -r '.result.data[0].parsedJson.registry_id'
    )
    if [ -n "$TRIBE_REGISTRY_ID" ] && [ "$TRIBE_REGISTRY_ID" != "null" ]; then
      echo "  VITE_TRIBE_REGISTRY_ID=$TRIBE_REGISTRY_ID"
      write_env_var "VITE_TRIBE_REGISTRY_ID" "$TRIBE_REGISTRY_ID" "$ENV_FILE"
      if [ -f "$WEB_ENV_FILE" ]; then
        write_env_var "VITE_TRIBE_REGISTRY_ID" "$TRIBE_REGISTRY_ID" "$WEB_ENV_FILE"
      fi
    else
      echo "  WARNING: Could not extract TribeRegistry ID from publish events" >&2
    fi
  fi

  if [ "$pkg" = "assembly_metadata" ]; then
    echo "  Querying MetadataRegistry shared object ID..."
    METADATA_REGISTRY_ID=$(
      curl -s http://127.0.0.1:9000 -X POST \
        -H 'Content-Type: application/json' \
        -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"suix_queryEvents\",\"params\":[{\"MoveEventType\":\"${PACKAGE_ID}::assembly_metadata::MetadataRegistryCreatedEvent\"},null,1,false]}" \
      | jq -r '.result.data[0].parsedJson.registry_id'
    )
    if [ -n "$METADATA_REGISTRY_ID" ] && [ "$METADATA_REGISTRY_ID" != "null" ]; then
      echo "  VITE_METADATA_REGISTRY_ID=$METADATA_REGISTRY_ID"
      write_env_var "VITE_METADATA_REGISTRY_ID" "$METADATA_REGISTRY_ID" "$ENV_FILE"
      if [ -f "$WEB_ENV_FILE" ]; then
        write_env_var "VITE_METADATA_REGISTRY_ID" "$METADATA_REGISTRY_ID" "$WEB_ENV_FILE"
      fi
    else
      echo "  WARNING: Could not extract MetadataRegistry ID from publish events" >&2
    fi
  fi
done

# ── Create CormConfig (post-deploy admin setup) ──────────────────
# The permissionless `install` function requires a shared CormConfig
# object on-chain. We create it here using the CormAdminCap (owned by
# the publisher from corm_auth init) and the brain address.
CORM_AUTH_PKG=$(grep '^PACKAGE_CORM_AUTH=' "$ENV_FILE" | cut -d= -f2)
CORM_STATE_PKG=$(grep '^PACKAGE_CORM_STATE=' "$ENV_FILE" | cut -d= -f2)

if [ -n "$CORM_AUTH_PKG" ] && [ -n "$CORM_STATE_PKG" ]; then
  echo ""
  echo "Creating CormConfig..."

  PUBLISHER_ADDR=$(sui client active-address)

  # Find CormAdminCap owned by the publisher
  ADMIN_CAP_ID=$(
    curl -s http://127.0.0.1:9000 -X POST \
      -H 'Content-Type: application/json' \
      -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"suix_getOwnedObjects\",\"params\":[\"$PUBLISHER_ADDR\",{\"filter\":{\"StructType\":\"${CORM_AUTH_PKG}::corm_auth::CormAdminCap\"},\"options\":{\"showType\":true}},null,1]}" \
    | jq -r '.result.data[0].data.objectId'
  )

  if [ -z "$ADMIN_CAP_ID" ] || [ "$ADMIN_CAP_ID" = "null" ]; then
    echo "  WARNING: Could not find CormAdminCap. Skipping CormConfig creation." >&2
  else
    # For localnet, use the publisher's own address as the brain address.
    # The continuity-engine service runs on the same keypair in local dev.
    BRAIN_ADDRESS="$PUBLISHER_ADDR"
    echo "  CormAdminCap: $ADMIN_CAP_ID"
    echo "  Brain address: $BRAIN_ADDRESS"

    sui client call \
      --package "$CORM_STATE_PKG" \
      --module corm_state \
      --function create_config \
      --args "$ADMIN_CAP_ID" "$BRAIN_ADDRESS" \
      --gas-budget "$GAS_BUDGET" \
      --json > /tmp/create-config-result.json 2>&1 || {
      echo "  ERROR: create_config call failed" >&2
      cat /tmp/create-config-result.json >&2
    }

    CORM_CONFIG_ID=$(
      jq -r '(.changed_objects // .objectChanges // [])[] | select(.idOperation == "CREATED" or .type == "created") | select(.objectType | contains("CormConfig")) | .objectId' /tmp/create-config-result.json
    )

    if [ -n "$CORM_CONFIG_ID" ] && [ "$CORM_CONFIG_ID" != "null" ]; then
      echo "  VITE_CORM_CONFIG_ID=$CORM_CONFIG_ID"
      write_env_var "VITE_CORM_CONFIG_ID" "$CORM_CONFIG_ID" "$ENV_FILE"
      if [ -f "$WEB_ENV_FILE" ]; then
        write_env_var "VITE_CORM_CONFIG_ID" "$CORM_CONFIG_ID" "$WEB_ENV_FILE"
      fi
    else
      echo "  WARNING: Could not extract CormConfig ID from create_config result" >&2
    fi

    rm -f /tmp/create-config-result.json
  fi
else
  echo ""
  echo "WARNING: corm_auth or corm_state package not found. Skipping CormConfig creation." >&2
fi

echo ""
echo "All contracts published. Package IDs written to:"
echo "  $ENV_FILE"
[ -f "$WEB_ENV_FILE" ] && echo "  $WEB_ENV_FILE"
